import {instructions} from './howToCreate'
import picture01 from '../content/recipes_img/carbonara.jpg';
import picture02 from '../content/recipes_img/caesar.jpg';
import picture03 from '../content/recipes_img/greek.jpeg';
import picture04 from '../content/recipes_img/curry.jpg';
import picture05 from '../content/recipes_img/margherita.jpeg';
import picture06 from '../content/recipes_img/omelete.jpg';
import picture07 from '../content/recipes_img/chiken-rise.jpg';
import picture08 from '../content/recipes_img/salmon.jpg';
import picture09 from '../content/recipes_img/tomate-soup.jpeg';
import picture10 from '../content/recipes_img/baked-potato.jpeg';
import picture11 from '../content/recipes_img/kebab.jpg';
import picture12 from '../content/recipes_img/orange-fresh.jpeg';
import picture13 from '../content/recipes_img/mexican_fajitos.jpg';
import picture14 from '../content/recipes_img/spagetti.jpg';
import picture15 from '../content/recipes_img/pancakes.jpg';
import picture16 from '../content/recipes_img/cheese-sticks.jpg';
import picture17 from '../content/recipes_img/krevetki.jpeg';
import picture18 from '../content/recipes_img/salmon-soup.jpeg';
import picture19 from '../content/recipes_img/choco-muss.jpeg';
import picture20 from '../content/recipes_img/chiken-teriyaki.jpeg';
import picture21 from '../content/recipes_img/lasagna.jpg';
import picture22 from '../content/recipes_img/burger.jpeg';
import picture23 from '../content/recipes_img/almond-cake.jpg';
import picture24 from '../content/recipes_img/eggplants.jpg';
import picture25 from '../content/recipes_img/pinacolada.jpg';

const recipes = [
  {
    id: 1,
    title: "Паста карбонара",
    link: "pasta-carbonara",
    description: "Итальянское блюдо из спагетти, яиц, гуанчиале (или бекона), сыра пармезан и перца.",
    picture: picture01,
    pictureBig: picture01,
    likes: 150,
    type:'hot',
    howToCreate: instructions[0].howToCreate,
  },
  {
    id: 2,
    title: "Салат Цезарь",
    link: "caesar-salad",
    description: "Салат из листьев романо, куриного мяса, гренок, пармезана, соуса Цезарь.",
    picture: picture02,
    pictureBig: picture02,
    likes: 120,
    type:'salad',
    howToCreate: instructions[1].howToCreate,
  },
  {
    id: 3,
    title: "Греческий салат",
    link: "greek-salad",
    description: "Салат с помидорами, огурцами, красным луком, оливками, фета-сыром, маслинами и оливковым маслом.",
    picture: picture03,
    pictureBig: picture03,
    likes: 200,
    type:'salad',
    howToCreate: instructions[2].howToCreate,
  },
  {
    id: 4,
    title: "Карри с курицей",
    link: "chicken-curry",
    description: "Индийское блюдо с куриной грудкой, кокосовым молоком, специями и базмати-рисом.",
    picture: picture04,
    pictureBig: picture04,
    likes: 180,
    type:'hot',
    howToCreate: instructions[3].howToCreate,
  },
  {
    id: 5,
    title: "Пицца Маргарита",
    link: "margherita-pizza",
    description: "Классическая итальянская пицца с томатным соусом, моцареллой и базиликом.",
    picture: picture05,
    pictureBig: picture05,
    likes: 250,
    type:'hot',
    howToCreate: instructions[4].howToCreate,
  },
  {
    id: 6,
    title: "Омлет с овощами",
    link: "vegetable-omelette",
    description: "Яичный омлет с помидорами, шпинатом, перцем и сыром.",
    picture: picture06,
    pictureBig: picture06,
    likes: 130,
    type:'hot',
    howToCreate: instructions[5].howToCreate,
  },
  {
    id: 7,
    title: "Рис с курицей и овощами",
    link: "chicken-vegetable-rice",
    description: "Паровой рис с обжаренной куриной грудкой, брокколи и морковью.",
    picture: picture07,
    pictureBig: picture07,
    likes: 160,
    type:'hot',
    howToCreate: instructions[6].howToCreate,
  },
  {
    id: 8,
    title: "Лосось с лимоном и зеленью",
    link: "salmon-lemon-herbs",
    description: "Печеный лосось с лимоном, розмарином и зелеными травами.",
    picture: picture08,
    pictureBig: picture08,
    likes: 190,
    type:'hot',
    howToCreate: instructions[7].howToCreate,
  },
  {
    id: 9,
    title: "Томатный суп",
    link: "tomato-soup",
    description: "Густой суп из спелых помидоров, базилика и сливок.",
    picture: picture09,
    pictureBig: picture09,
    likes: 120,
    type:'soup',
    howToCreate: instructions[8].howToCreate,
  },
  {
    id: 10,
    title: "Печеная картошка с розмарином",
    link: "baked-potatoes-rosemary",
    description: "Картошка, запеченная в духовке с оливковым маслом, розмарином и чесноком.",
    picture: picture10,
    pictureBig: picture10,
    likes: 140,
    type:'hot',
    howToCreate: instructions[9].howToCreate,
  },
  {
    id: 11,
    title: "Куриные кебабы",
    link: "chicken-kebabs",
    description: "Куриные кебабы с пряными специями, подаваемые с тандырным хлебом.",
    picture: picture11,
    pictureBig: picture11,
    likes: 170,
    type:'hot',
    howToCreate: instructions[10].howToCreate,
  },
  {
    id: 12,
    title: "Фреш из апельсинов",
    link: "orange-juice-fresh",
    description: "Освежающий фреш из свежевыжатого апельсинового сока.",
    picture: picture12,
    pictureBig: picture12,
    likes: 110,
    type:'drink',
    howToCreate: instructions[11].howToCreate,
  },
  {
    id: 13,
    title: "Мексиканские фаджитас",
    link: "mexican-fajitas",
    description: "Мексиканская закуска с обжаренным мясом, луком, перцем и тортильей.",
    picture: picture13,
    pictureBig: picture13,
    likes: 200,
    type:'snack',
    howToCreate: instructions[12].howToCreate,
  },
  {
    id: 14,
    title: "Спагетти с томатным соусом",
    link: "spaghetti-tomato-sauce",
    description: "Спагетти с томатным соусом, чесноком и базиликом.",
    picture: picture14,
    pictureBig: picture14,
    likes: 160,
    type:'hot',
    howToCreate: instructions[13].howToCreate,
  },
  {
    id: 15,
    title: "Блинчики с кленовым сиропом",
    link: "pancakes-maple-syrup",
    description: "Легкие блинчики, подаваемые с кленовым сиропом и маслом.",
    picture: picture15,
    pictureBig: picture15,
    likes: 180,
    type:'hot',
    howToCreate: instructions[14].howToCreate,
  },
  {
    id: 16,
    title: "Сырные палочки",
    link: "cheese-sticks",
    description: "Хрустящие палочки из теста с сыром, подаваемые с соусом.",
    picture: picture16,
    pictureBig: picture16,
    likes: 120,
    type:'snack',
    howToCreate: instructions[15].howToCreate,
  },
  {
    id: 17,
    title: "Креветки в чесночном соусе",
    link: "shrimp-garlic-sauce",
    description: "Креветки, обжаренные в чесночном соусе, подаваемые с лимоном и зеленью.",
    picture: picture17,
    pictureBig: picture17,
    likes: 220,
    type:'snack',
    howToCreate: instructions[16].howToCreate,
  },
  {
    id: 18,
    title: "Суп с лососем и картошкой",
    link: "salmon-potato-soup",
    description: "Сытный суп с лососем, картошкой и овощами.",
    picture: picture18,
    pictureBig: picture18,
    likes: 190,
    type:'soup',
    howToCreate: instructions[17].howToCreate,
  },
  {
    id: 19,
    title: "Шоколадный мусс",
    link: "chocolate-mousse",
    description: "Нежный шоколадный мусс, украшенный ягодами и мятой.",
    picture: picture19,
    pictureBig: picture19,
    likes: 250,
    type:'dessert',
    howToCreate: instructions[18].howToCreate,
  },
  {
    id: 20,
    title: "Курица терияки",
    link: "chicken-teriyaki",
    description: "Курица, маринованная в терияки соусе, подаваемая с овощами и рисом.",
    picture: picture20,
    pictureBig: picture20,
    likes: 170,
    type:'hot',
    howToCreate: instructions[19].howToCreate,
  },
  {
    id: 21,
    title: "Лазанья",
    link: "lasagna",
    description: "Печеные слои теста с мясным соусом, бешамелью и сыром.",
    picture: picture21,
    pictureBig: picture21,
    likes: 200,
    type:'hot',
    howToCreate: instructions[20].howToCreate,
  },
  {
    id: 22,
    title: "Бургер с говяжьей котлетой",
    link: "beef-burger",
    description: "Сочный бургер с говяжьей котлетой, салатом, помидором и соусом.",
    picture: picture22,
    pictureBig: picture22,
    likes: 180,
    type:'hot',
    howToCreate: instructions[21].howToCreate,
  },
  {
    id: 23,
    title: "Миндальный кекс",
    link: "almond-cake",
    description: "Нежный кекс с добавлением молотых миндальных орехов.",
    picture: picture23,
    pictureBig: picture23,
    likes: 160,
    type:'dessert',
    howToCreate: instructions[22].howToCreate,
  },
  {
    id: 24,
    title: "Фаршированные баклажаны",
    link: "stuffed-eggplants",
    description: "Баклажаны, фаршированные мясом, овощами и запеченные в духовке.",
    picture: picture24,
    pictureBig: picture24,
    likes: 210,
    type:'hot',
    howToCreate: instructions[23].howToCreate,
  },
  {
    id: 25,
    title: "Коктейль Пина Колада",
    link: "pinacolada-cocktail",
    description: "Тропический коктейль с ромом, кокосовым молоком и ананасовым соком.",
    picture: picture25,
    pictureBig: picture25,
    likes: 240,
    type:'drink',
    howToCreate: instructions[24].howToCreate,
  },
  // Допиши оставшиеся элементы
];


export { recipes };